using Modern.DataAccessLayer.IRepository;
using Modern.Object.Models;
using System.Collections.Generic;

namespace Modern.DataAccessLayer.Repository
{
    public class GamesRepository : IGamesRepository
    {
        public List<Game> GetGamesList()
        {
            var gameList = new List<Game> {
                new Game { background_Image="https://ichef.bbci.co.uk/news/800/cpsprodpb/13729/production/_112375697_1331db7a-17c0-4401-8cac-6a2309ff49b6.jpg", description="Battel Game", metacritic=3, metacritic_Url="", name="Battel Game", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                new Game { background_Image="https://ichef.bbci.co.uk/news/976/cpsprodpb/11E3/production/_113897540_halo_infinite_keyart_primary_horiz.jpg", description="Infinite Keyart", metacritic=3, metacritic_Url="", name="Netflix-style service for video games", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                new Game { background_Image="https://images.ctfassets.net/5lpapfxq15sk/2wrbN1qNfnCxiiOlwZXWXm/2496a832b7a09e7ae01bf04487a92c02/NW-thumb.jpg", description="New World", metacritic=3, metacritic_Url="", name="New World", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                new Game { background_Image="https://cdn.vox-cdn.com/thumbor/Xm1C9TWbMK55zAnuR09oD6XMyRI=/0x0:1024x1024/1200x800/filters:focal(444x567:606x729)/cdn.vox-cdn.com/uploads/chorus_image/image/65813576/mobile_MarioKartTour_screen_01.0.png", description="Mario Kart Tour", metacritic=3, metacritic_Url="", name="Mario Kart Tour", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } }
                //new Game { background_Image="https://insomniac.games/wp-content/uploads/2020/10/RCRA_RiftApart_Keyart_1080x1080.jpg", description="Ratched & Clank", metacritic=3, metacritic_Url="", name="Ratched & Clank", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                //new Game { background_Image="https://insomniac.games/wp-content/uploads/2019/08/MSM_KeyArt_Final_1080x1080.jpg", description="Marvel's Spider-Man", metacritic=3, metacritic_Url="", name="Marvel's Spider-Man", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                //new Game { background_Image="https://insomniac.games/wp-content/uploads/2018/06/stormland_square.jpg", description="StromLand", metacritic=3, metacritic_Url="", name="StromLand", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                //new Game { background_Image="https://insomniac.games/wp-content/uploads/2017/07/game_title_feral_rites.jpg", description="Feral Rites", metacritic=3, metacritic_Url="", name="Feral Rites", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                //new Game { background_Image="https://insomniac.games/wp-content/uploads/2017/07/game_title_song_of_the_deep.jpg", description="Song of the Deep", metacritic=3, metacritic_Url="", name="Song of the Deep", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                //new Game { background_Image="https://insomniac.games/wp-content/uploads/2017/07/game_title_edge_of_nowhere.jpg", description="Edge of Nowhere", metacritic=3, metacritic_Url="", name="Edge of Nowhere", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
                //new Game { background_Image="https://insomniac.games/wp-content/uploads/2017/07/game_title_the_unspken.jpg", description="The UnSpoken", metacritic=3, metacritic_Url="", name="The UnSpoken", released="", website="", parentPlatForms =new List<ParentPlatForm> { new ParentPlatForm { platForm = "https://www.freepnglogos.com/uploads/xbox-logo-black-png-7.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/1670/1670670.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5685/5685258.png" }, new ParentPlatForm { platForm = "https://cdn-icons-png.flaticon.com/512/5705/5705036.png" } } },
            };

            return gameList;
        }
    }
}
